default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } + 100  %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: solobania_development

test:
  <<: *default
  database: solobania_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
