source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.0.4", ">= 7.0.4.3"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "tzinfo-data"

group :development, :test do
  gem "bundle-audit"
  gem "debug"
  gem "factory_bot_rails"
  gem "faker"
  gem "guard"
  gem "guard-rspec"
  gem "rspec-rails", "~> 4.0.0"
  gem "rubocop"
  gem "spring-commands-rspec"
  gem "webmock"
end

group :development do
  gem "listen", "~> 3.3"
  gem "rails-erd"
  gem "spring"
  gem "spring-watcher-listen"
end

